### ISSUE TITLE
multiple deployments from travis-ci

### ISSUE THREAD

**Issue by GliderGeek** [Turbo87/aerofiles#32]
The latest CI run shows an error during the deployment phase, because it tries to deploy on each entry in the test matrix (every version of python against which the tests are run). This deployment is successful for the python version which finishes testing first, but fails for the others: the package is already present on pypi.

This can be fixed in `.travic.yml` by adding that it should only deploy on the latest python version:

```
deploy:
  provider: pypi
  user: Tobias.Bieniek
  password:
    secure: 'encrypted password'
  on:
    tags: true
    python: latest
    repo: Turbo87/aerofiles
```

EDIT:
i am not certain whether `python: latest` works. the travis-ci doc only gives an example with a specific version number. thus: `python: '3.6'`

Sources:
https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A
https://stackoverflow.com/a/41543235/4629173
